remote_theme: dieghernan/chulapa

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
    
url: "https://microbiomehelper.ca"
baseurl: "/MicrobiomeHelper2"

theme: null

chulapa-skin:
  skin: "Solar" # Options include: NAVI, ZENBURN, FLATLY, etc.
  highlight: "cobalt2" # Controls code snippet styling
