url: "http://microbiomehelper.ca"

baseurl: ""

title: "Microbiome Helper"
description: "Resources for microbiome data analysis"

remote_theme: dieghernan/chulapa
theme: null

chulapa-skin:
  skin: "solar"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  
navbar:
  menu: "navigation"
  color: "dark" 