url: "http://microbiomehelper.ca"
baseurl: ""

remote_theme: dieghernan/chulapa
theme: null
chulapa-skin:
  skin: "solar"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  
navbar:
  menu: "navigation"